-- Feature Signal Upgrade scaffold (non-destructive)
-- Creates FEAT_SIG schema, versioned feature tables, and feature build audit table.

CREATE DATABASE IF NOT EXISTS EY_WQ;
CREATE SCHEMA IF NOT EXISTS EY_WQ.FEAT_SIG;
CREATE SCHEMA IF NOT EXISTS EY_WQ.AUDIT;

CREATE TABLE IF NOT EXISTS EY_WQ.AUDIT.FEATURE_BUILD_REGISTRY (
    BUILT_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    FEATURE_VERSION STRING,
    BUILD_STEP STRING,
    OUTPUT_TABLE STRING,
    SOURCE_TABLES STRING,
    SQL_HASH STRING,
    ROW_COUNT NUMBER,
    NOTES STRING
);

-- Family A: basin/catchment context (v1)
CREATE OR REPLACE TABLE EY_WQ.FEAT_SIG.STATION_CONTEXT_V1 AS
SELECT
    LATITUDE,
    LONGITUDE,
    ELEVATION,
    SLOPE,
    BASIN_AREA_KM2,
    UPSTREAM_AREA_KM2,
    CATCH_TO_BASIN_RATIO,
    DIST_TO_RIVER_M,
    RIVER_DISCHARGE_CMS,
    SOIL_CLAY_0_5,
    SOIL_PH_0_5,
    SOIL_SOC_0_5,
    LANDCOVER,
    UPSTREAM_AREA_KM2 * SLOPE AS AREA_X_SLOPE,
    SOIL_PH_0_5 * UPSTREAM_AREA_KM2 AS PH_X_AREA,
    SOIL_CLAY_0_5 * UPSTREAM_AREA_KM2 AS CLAY_X_AREA,
    UPSTREAM_AREA_KM2 / (RIVER_DISCHARGE_CMS + 1.0) AS DISCHARGE_CONTACT_PROXY
FROM EY_WQ.RAW.EXTERNAL_GEOFEATURES_PLUS_HYDRO_V2;

-- Family B: temporal memory for train (v1)
CREATE OR REPLACE TABLE EY_WQ.FEAT_SIG.TEMPORAL_MEMORY_V1_TRAIN AS
SELECT
    LATITUDE,
    LONGITUDE,
    SAMPLE_DATE,
    CHIRPS_PPT,
    LAG(CHIRPS_PPT, 1) OVER (PARTITION BY LATITUDE, LONGITUDE ORDER BY SAMPLE_DATE) AS RAIN_LAG_1,
    LAG(CHIRPS_PPT, 3) OVER (PARTITION BY LATITUDE, LONGITUDE ORDER BY SAMPLE_DATE) AS RAIN_LAG_3,
    LAG(CHIRPS_PPT, 7) OVER (PARTITION BY LATITUDE, LONGITUDE ORDER BY SAMPLE_DATE) AS RAIN_LAG_7,
    SUM(CHIRPS_PPT) OVER (
        PARTITION BY LATITUDE, LONGITUDE ORDER BY SAMPLE_DATE
        ROWS BETWEEN 30 PRECEDING AND 1 PRECEDING
    ) AS RAIN_ROLL_30,
    SUM(CHIRPS_PPT) OVER (
        PARTITION BY LATITUDE, LONGITUDE ORDER BY SAMPLE_DATE
        ROWS BETWEEN 60 PRECEDING AND 1 PRECEDING
    ) AS RAIN_ROLL_60,
    SUM(CHIRPS_PPT) OVER (
        PARTITION BY LATITUDE, LONGITUDE ORDER BY SAMPLE_DATE
        ROWS BETWEEN 90 PRECEDING AND 1 PRECEDING
    ) AS RAIN_ROLL_90,
    DAYOFYEAR(SAMPLE_DATE) AS DOY,
    MONTH(SAMPLE_DATE) AS MONTH_NUM,
    SIN(2 * PI() * DAYOFYEAR(SAMPLE_DATE) / 365.0) AS SIN_DOY,
    COS(2 * PI() * DAYOFYEAR(SAMPLE_DATE) / 365.0) AS COS_DOY,
    SIN(2 * PI() * MONTH(SAMPLE_DATE) / 12.0) AS SIN_MONTH,
    COS(2 * PI() * MONTH(SAMPLE_DATE) / 12.0) AS COS_MONTH
FROM EY_WQ.RAW.CHIRPS_FEATURES_TRAINING;

-- Family B: temporal memory for valid (v1)
CREATE OR REPLACE TABLE EY_WQ.FEAT_SIG.TEMPORAL_MEMORY_V1_VALID AS
SELECT
    LATITUDE,
    LONGITUDE,
    SAMPLE_DATE,
    CHIRPS_PPT,
    LAG(CHIRPS_PPT, 1) OVER (PARTITION BY LATITUDE, LONGITUDE ORDER BY SAMPLE_DATE) AS RAIN_LAG_1,
    LAG(CHIRPS_PPT, 3) OVER (PARTITION BY LATITUDE, LONGITUDE ORDER BY SAMPLE_DATE) AS RAIN_LAG_3,
    LAG(CHIRPS_PPT, 7) OVER (PARTITION BY LATITUDE, LONGITUDE ORDER BY SAMPLE_DATE) AS RAIN_LAG_7,
    SUM(CHIRPS_PPT) OVER (
        PARTITION BY LATITUDE, LONGITUDE ORDER BY SAMPLE_DATE
        ROWS BETWEEN 30 PRECEDING AND 1 PRECEDING
    ) AS RAIN_ROLL_30,
    SUM(CHIRPS_PPT) OVER (
        PARTITION BY LATITUDE, LONGITUDE ORDER BY SAMPLE_DATE
        ROWS BETWEEN 60 PRECEDING AND 1 PRECEDING
    ) AS RAIN_ROLL_60,
    SUM(CHIRPS_PPT) OVER (
        PARTITION BY LATITUDE, LONGITUDE ORDER BY SAMPLE_DATE
        ROWS BETWEEN 90 PRECEDING AND 1 PRECEDING
    ) AS RAIN_ROLL_90,
    DAYOFYEAR(SAMPLE_DATE) AS DOY,
    MONTH(SAMPLE_DATE) AS MONTH_NUM,
    SIN(2 * PI() * DAYOFYEAR(SAMPLE_DATE) / 365.0) AS SIN_DOY,
    COS(2 * PI() * DAYOFYEAR(SAMPLE_DATE) / 365.0) AS COS_DOY,
    SIN(2 * PI() * MONTH(SAMPLE_DATE) / 12.0) AS SIN_MONTH,
    COS(2 * PI() * MONTH(SAMPLE_DATE) / 12.0) AS COS_MONTH
FROM EY_WQ.RAW.CHIRPS_FEATURES_VALIDATION;

-- Family C: upstream pressure proxies for train (v1)
CREATE OR REPLACE TABLE EY_WQ.FEAT_SIG.UPSTREAM_PRESSURE_V1_TRAIN AS
SELECT
    tm.LATITUDE,
    tm.LONGITUDE,
    tm.SAMPLE_DATE,
    sc.UPSTREAM_AREA_KM2 * COALESCE(sc.CROPLAND_FRACTION_5KM, 0) AS UPSTREAM_CROPLAND_PRESSURE,
    sc.UPSTREAM_AREA_KM2 * COALESCE(sc.URBAN_FRACTION_5KM, 0) AS UPSTREAM_URBAN_PRESSURE,
    sc.UPSTREAM_AREA_KM2 * COALESCE(sc.SOIL_CLAY_0_5, 0) AS UPSTREAM_SOIL_CLAY_PRESSURE,
    sc.UPSTREAM_AREA_KM2 * COALESCE(sc.SOIL_SOC_0_5, 0) AS UPSTREAM_SOC_PRESSURE,
    sc.UPSTREAM_AREA_KM2 * COALESCE(tm.RAIN_ROLL_30, 0) AS UPSTREAM_RAIN_30D_PRESSURE,
    sc.UPSTREAM_AREA_KM2 * COALESCE(tm.RAIN_ROLL_60, 0) AS UPSTREAM_RAIN_60D_PRESSURE,
    (sc.UPSTREAM_AREA_KM2 * COALESCE(tm.RAIN_ROLL_30, 0)) / (COALESCE(sc.RIVER_DISCHARGE_CMS, 0) + 1.0) AS NUTRIENT_TRANSPORT_PROXY,
    COALESCE(tm.RAIN_ROLL_30, 0) * COALESCE(sc.SLOPE, 0) * EXP(-COALESCE(sc.DIST_TO_RIVER_M, 0) / 5000.0) AS RUNOFF_TRANSFER_INDEX,
    sc.UPSTREAM_AREA_KM2 / (COALESCE(sc.DIST_TO_RIVER_M, 0) + 1.0) AS CONNECTIVITY_PROXY,
    sc.UPSTREAM_AREA_KM2 * COALESCE(sc.SLOPE, 0) AS STREAM_POWER_PROXY
FROM EY_WQ.FEAT_SIG.TEMPORAL_MEMORY_V1_TRAIN tm
LEFT JOIN EY_WQ.FEAT_SIG.STATION_CONTEXT_V1 sc
USING (LATITUDE, LONGITUDE);

-- Family C: upstream pressure proxies for valid (v1)
CREATE OR REPLACE TABLE EY_WQ.FEAT_SIG.UPSTREAM_PRESSURE_V1_VALID AS
SELECT
    tm.LATITUDE,
    tm.LONGITUDE,
    tm.SAMPLE_DATE,
    sc.UPSTREAM_AREA_KM2 * COALESCE(sc.CROPLAND_FRACTION_5KM, 0) AS UPSTREAM_CROPLAND_PRESSURE,
    sc.UPSTREAM_AREA_KM2 * COALESCE(sc.URBAN_FRACTION_5KM, 0) AS UPSTREAM_URBAN_PRESSURE,
    sc.UPSTREAM_AREA_KM2 * COALESCE(sc.SOIL_CLAY_0_5, 0) AS UPSTREAM_SOIL_CLAY_PRESSURE,
    sc.UPSTREAM_AREA_KM2 * COALESCE(sc.SOIL_SOC_0_5, 0) AS UPSTREAM_SOC_PRESSURE,
    sc.UPSTREAM_AREA_KM2 * COALESCE(tm.RAIN_ROLL_30, 0) AS UPSTREAM_RAIN_30D_PRESSURE,
    sc.UPSTREAM_AREA_KM2 * COALESCE(tm.RAIN_ROLL_60, 0) AS UPSTREAM_RAIN_60D_PRESSURE,
    (sc.UPSTREAM_AREA_KM2 * COALESCE(tm.RAIN_ROLL_30, 0)) / (COALESCE(sc.RIVER_DISCHARGE_CMS, 0) + 1.0) AS NUTRIENT_TRANSPORT_PROXY,
    COALESCE(tm.RAIN_ROLL_30, 0) * COALESCE(sc.SLOPE, 0) * EXP(-COALESCE(sc.DIST_TO_RIVER_M, 0) / 5000.0) AS RUNOFF_TRANSFER_INDEX,
    sc.UPSTREAM_AREA_KM2 / (COALESCE(sc.DIST_TO_RIVER_M, 0) + 1.0) AS CONNECTIVITY_PROXY,
    sc.UPSTREAM_AREA_KM2 * COALESCE(sc.SLOPE, 0) AS STREAM_POWER_PROXY
FROM EY_WQ.FEAT_SIG.TEMPORAL_MEMORY_V1_VALID tm
LEFT JOIN EY_WQ.FEAT_SIG.STATION_CONTEXT_V1 sc
USING (LATITUDE, LONGITUDE);

-- Versioned modelready tables to consume in local training exports
CREATE OR REPLACE TABLE EY_WQ.FEAT_SIG.TRAIN_MODELREADY_SIG_V1 AS
SELECT
    m.*,
    tm.RAIN_LAG_1,
    tm.RAIN_LAG_3,
    tm.RAIN_LAG_7,
    tm.RAIN_ROLL_30,
    tm.RAIN_ROLL_60,
    tm.RAIN_ROLL_90,
    tm.SIN_DOY,
    tm.COS_DOY,
    tm.SIN_MONTH,
    tm.COS_MONTH,
    up.UPSTREAM_CROPLAND_PRESSURE,
    up.UPSTREAM_URBAN_PRESSURE,
    up.UPSTREAM_SOIL_CLAY_PRESSURE,
    up.UPSTREAM_SOC_PRESSURE,
    up.UPSTREAM_RAIN_30D_PRESSURE,
    up.UPSTREAM_RAIN_60D_PRESSURE,
    up.NUTRIENT_TRANSPORT_PROXY,
    up.RUNOFF_TRANSFER_INDEX,
    up.CONNECTIVITY_PROXY,
    up.STREAM_POWER_PROXY
FROM EY_WQ.MART.TRAIN_MODELREADY m
LEFT JOIN EY_WQ.FEAT_SIG.TEMPORAL_MEMORY_V1_TRAIN tm
USING (LATITUDE, LONGITUDE, SAMPLE_DATE)
LEFT JOIN EY_WQ.FEAT_SIG.UPSTREAM_PRESSURE_V1_TRAIN up
USING (LATITUDE, LONGITUDE, SAMPLE_DATE);

CREATE OR REPLACE TABLE EY_WQ.FEAT_SIG.VALID_MODELREADY_SIG_V1 AS
SELECT
    m.*,
    tm.RAIN_LAG_1,
    tm.RAIN_LAG_3,
    tm.RAIN_LAG_7,
    tm.RAIN_ROLL_30,
    tm.RAIN_ROLL_60,
    tm.RAIN_ROLL_90,
    tm.SIN_DOY,
    tm.COS_DOY,
    tm.SIN_MONTH,
    tm.COS_MONTH,
    up.UPSTREAM_CROPLAND_PRESSURE,
    up.UPSTREAM_URBAN_PRESSURE,
    up.UPSTREAM_SOIL_CLAY_PRESSURE,
    up.UPSTREAM_SOC_PRESSURE,
    up.UPSTREAM_RAIN_30D_PRESSURE,
    up.UPSTREAM_RAIN_60D_PRESSURE,
    up.NUTRIENT_TRANSPORT_PROXY,
    up.RUNOFF_TRANSFER_INDEX,
    up.CONNECTIVITY_PROXY,
    up.STREAM_POWER_PROXY
FROM EY_WQ.MART.VALID_MODELREADY m
LEFT JOIN EY_WQ.FEAT_SIG.TEMPORAL_MEMORY_V1_VALID tm
USING (LATITUDE, LONGITUDE, SAMPLE_DATE)
LEFT JOIN EY_WQ.FEAT_SIG.UPSTREAM_PRESSURE_V1_VALID up
USING (LATITUDE, LONGITUDE, SAMPLE_DATE);
