-- Minimal Snowflake model-ready table build for EY Water Quality Challenge
-- Keeps local Python training flow intact while accelerating joins/audit.

CREATE DATABASE IF NOT EXISTS EY_WQ;

CREATE SCHEMA IF NOT EXISTS EY_WQ.RAW;
CREATE SCHEMA IF NOT EXISTS EY_WQ.MART;
CREATE SCHEMA IF NOT EXISTS EY_WQ.AUDIT;

-- TRAIN_MODELREADY
CREATE OR REPLACE TABLE EY_WQ.MART.TRAIN_MODELREADY AS
SELECT
    wq.*,
    ls.* EXCLUDE (LATITUDE, LONGITUDE, SAMPLE_DATE),
    tc.* EXCLUDE (LATITUDE, LONGITUDE, SAMPLE_DATE),
    ch.* EXCLUDE (LATITUDE, LONGITUDE, SAMPLE_DATE),
    ext.* EXCLUDE (LATITUDE, LONGITUDE)
FROM EY_WQ.RAW.WATER_QUALITY_TRAINING_DATASET wq
INNER JOIN EY_WQ.RAW.LANDSAT_FEATURES_TRAINING ls
    USING (LATITUDE, LONGITUDE, SAMPLE_DATE)
INNER JOIN EY_WQ.RAW.TERRACLIMATE_FEATURES_TRAINING tc
    USING (LATITUDE, LONGITUDE, SAMPLE_DATE)
LEFT JOIN EY_WQ.RAW.CHIRPS_FEATURES_TRAINING ch
    USING (LATITUDE, LONGITUDE, SAMPLE_DATE)
LEFT JOIN EY_WQ.RAW.EXTERNAL_GEOFEATURES_PLUS_HYDRO_V2 ext
    USING (LATITUDE, LONGITUDE);

-- VALID_MODELREADY
CREATE OR REPLACE TABLE EY_WQ.MART.VALID_MODELREADY AS
SELECT
    st.*,
    ls.* EXCLUDE (LATITUDE, LONGITUDE, SAMPLE_DATE),
    tc.* EXCLUDE (LATITUDE, LONGITUDE, SAMPLE_DATE),
    ch.* EXCLUDE (LATITUDE, LONGITUDE, SAMPLE_DATE),
    ext.* EXCLUDE (LATITUDE, LONGITUDE)
FROM EY_WQ.RAW.SUBMISSION_TEMPLATE st
LEFT JOIN EY_WQ.RAW.LANDSAT_FEATURES_VALIDATION ls
    USING (LATITUDE, LONGITUDE, SAMPLE_DATE)
LEFT JOIN EY_WQ.RAW.TERRACLIMATE_FEATURES_VALIDATION tc
    USING (LATITUDE, LONGITUDE, SAMPLE_DATE)
LEFT JOIN EY_WQ.RAW.CHIRPS_FEATURES_VALIDATION ch
    USING (LATITUDE, LONGITUDE, SAMPLE_DATE)
LEFT JOIN EY_WQ.RAW.EXTERNAL_GEOFEATURES_PLUS_HYDRO_V2 ext
    USING (LATITUDE, LONGITUDE);

-- Experiment registry table for reproducibility / audit
CREATE TABLE IF NOT EXISTS EY_WQ.AUDIT.EXPERIMENT_REGISTRY (
    REGISTERED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    RUN_ID STRING,
    RUN_PATH STRING,
    CONFIG_PATH STRING,
    CV_PATH STRING,
    TARGET_TA_MEAN FLOAT,
    TARGET_EC_MEAN FLOAT,
    TARGET_DRP_MEAN FLOAT,
    CV_MEAN FLOAT,
    DRP_MODEL STRING,
    DRP_Y_MODE STRING,
    TE_ENABLED BOOLEAN,
    NOTES STRING
);
